version: '3.8'

services:
  wellsy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    ports:
      - "5002:5000"

